### ISSUE TITLE
IPv6 address resolution

### ISSUE THREAD

**Issue by miyahirodazu** [trema/trema-edge#24]
Hi trema-team,
I tried ping6 on learning_switch with ofsoftswitch13, but it did not work well.
I could see NS in packet_in message, but cannot see packet_out message corresponding to it. Can trema-edge handle NS/NA?

Thanks,

**Comment by yasuhito** [comment]
I would like to hear from IPv6 experts. @sugyo san or @chibacchie san, any comments??

**Comment by chibacchie** [comment]
I suppose the root case of the issue is that ofsoftswitch13 does not conform with the protocol specification. More specifically the pre-requisite defined in the table 11 of the OpenFlow 1.3.1 specification requires to place OXM_OF_ICMPV6_TYPE before OXM_OF_IPV6_ND_TARGET but ofsoftswitch13 does not comply with it. You may find the following message in switch_daemon.[dpid].log.

```
Jun 19 11:07:31.868 [notice] Invalid openflow message. type:10, errno:-71
```

**Comment by miyahirodazu** [comment]
Hi Ciba-san,

Thanks for your information!

I'll check it.

...miyahirodazu

2013/06/19 11:29$B!"(BYasunobu Chiba notifications@github.com $B$N%a%C%;!<%8(B:

**Comment by miyahirodazu** [comment]
Hi Chiba-san,

Sorry for my slow response.
I have confirmed the message. But I cannot find the message you mentioned.

On the other hand, I have noticed that the packet in message from ofsoftswitch13 has wrong match field.

OXM field 
(Snip)
0100 000. = Field : Source link-layer for ND - OFPXMT_OFB_IPV6_ND_SSL (0x20)
(Snip)
Value: 01016805ca04

Actual Value shall be 6805ca049869

It means two bytes shifted.
It is a bug of ofsoftswitch13.

In addition, I have tried IPv6 with Trema-edge switch and openvswitch. And both works well with trema-edge controller.

This issue is based on a bug of ofsoftswitch13, we can close this issue.

Thanks so much!

...miyahirodazu
