### ISSUE TITLE
instructions cannot be extracted from FlowMultipartReply

### ISSUE THREAD

**Issue by chibacchie** [trema/trema-edge#31]
FlowMultipartReply does not have "insctuctions" and it is not possible to extract instructions from flow stats multipart reply.

**Comment by nickkaranatsios** [comment]
@chibacchie 
Currently in openflow.h (OPF1.3.1) (struct ofp_flow_stats) instructions are commented out. Probably instructions required that's why you raised this issue, I would start doing the mods to openflow.h, switch(datapath/switch) and rest of source, please wait for a while since there are lots of changes to be done.

**Comment by chibacchie** [comment]
Because struct ofp_match is variable length, "instructions" in struct ofp_flow_stats seems to be commented out (similar reason to struct ofp_flow_mod). C library (libtrema) supports to include instructions in struct ofp_flow_stats but Trema Switch and Ruby wrapper do not support it. Open vSwitch includes instructions as a part of flow stats multipart reply.

**Comment by nickkaranatsios** [comment]
@chibacchie 
This https://github.com/trema/trema-edge/commit/a4a245d2bebe43ac9e9c72394a365d842057a292 commit adds instructions to multipart flow stats reply. Pls confirm. PS. Do a clean build not sure where the problem is but apparently some dependencies don't work well for switch/switch and switch/datapath.

**Comment by chibacchie** [comment]
@nickkaranatsios Goooood! Thanks for the patch.
